#!/usr/bin/env bash
#ngnix script to install the web server

sudo apt-get update
sudo apt-get install -y nginx
sudo sh -c 'echo "Hello World!"> /var/www/html/index.html'
sudo service nginx restart


# # Script that install and configure it to listen on port 80
# # Print "Hello World"

# sudo apt-get update
# sudo apt-get -y install nginx
# echo 'Hello World!' > /var/www/html/index.html
# service nginx start

