#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer on a new Ubuntu machine

# Update the package list and install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# Define the HAProxy configuration
HAPROXY_CONFIG="/etc/haproxy/haproxy.cfg"

# Create the HAProxy configuration
sudo tee "$HAPROXY_CONFIG" > /dev/null << EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 317069-web-01 100.26.252.189:80 check
    server 317069-web-02 100.26.232.86:80 check
EOL

# Enable HAProxy to start at boot
sudo systemctl enable haproxy

# Start HAProxy
sudo systemctl restart haproxy
