#!/usr/bin/env bash
# Script that sets up Nginx to listen on port 80

# Install Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Ensure Nginx listens on port 80
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
