#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hour=0
min=1
while [ "$hour" -lt 12 ]
do
	echo "Hour: $hour" 
	while [ "$min" -lt 60 ]
	do
		echo "$min"
		((min++))
	done
	min=1
	((hour++))
done
