#!/usr/bin/env bash
# Bash script that gives you information about the school file.
f_name="school"
if [ -e "$f_name" ]
then
	echo "school file exits"
	if [ -e "$f_name" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$f_name" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
