#!/usr/bin/env bash
# Bash script that gives you information about the school file.
f_name="school"
if [ -e "$f_name" ]
then
	echo "$f_name file exits"
	if [ -s "$f_name" ]
	then
		echo "$f_name file is empty"
	else
		echo "$f_name file is not empty"
	fi
	if [ -f "$f_name" ]
	then
		echo "$f_name is a regular file"
	fi
else
	echo "$f_name file does not exist"
fi
