#!/usr/bin/env bash
# This script installs Apache, updates the default web page, and starts the Apache service

# Update the package list
apt-get update

# Install Apache
apt-get install -y apache2

# Write "Hello Holberton" to the default web page
echo 'Hello Holberton' > /var/www/html/index.html

# Start the Apache service
service apache2 start



# Check if Apache is running and output the required message
if service apache2 status | grep -q "running"; then
  echo "apache2 is running"
fi
